# Generated by Django 3.2 on 2022-02-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welltory', '0002_auto_20220213_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=100)),
                ('parameter_baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welltory.parameter')),
            ],
        ),
    ]
