# Generated by Django 3.2 on 2022-02-14 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('welltory', '0004_auto_20220214_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('dateOfBirth', models.DateField(null=True)),
                ('national_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welltory.practitioner')),
            ],
        ),
    ]
