# Generated by Django 3.2 on 2022-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
