# Generated by Django 3.2 on 2022-02-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welltory', '0007_diagnosis_dignosisdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='documents')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welltory.diagnosis')),
            ],
        ),
        migrations.DeleteModel(
            name='DignosisDoc',
        ),
    ]
