# Generated by Django 3.2 on 2022-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welltory', '0008_auto_20220215_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisdoc',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
